messages:
  # The prefix will be put in front of every message.
  # Set it to be empty to disable it.
  prefix: '&6&lPetsPlus &7>>'

  playersOnly: '&cThis command can only be used by players!'
  noPermission: '&cYou do not have permission to spawn this pet type!'

  alreadyHavePet: '&cYou already have a pet active!'
  spawnedPet: '&aSpawned your {} pet'
  despawnedPet: '&aDespawned your {} pet'

gui:
  titles:
    main: '&a&lPets'
    options: '&a&lPets &7| Options'

  ridePet: '&6Ride pet'
  makeSound: '&6Make sound'
  removePet: '&cRemove pet'

settings:
  # If set to true, pets will not make sound on their own.
  # They can still make sound if the 'Make sound' button is pressed.
  isSilent: true

  # If set to true, pets will have a nametag visible.
  hasNametag: true

# You can configure each pet type below.
# Disabling a mob type will prevent it from showing up in-game entirely.
petTypes:
  chicken:
    enabled: true
    name: 'Chicken'
  babyChicken:
    enabled: true
    name: 'Baby Chicken'
  cow:
    enabled: true
    name: 'Cow'
  babyCow:
    enabled: true
    name: 'Baby Cow'
  mushroom:
    enabled: true
    name: 'Mushroom'
  babyMushroom:
    enabled: true
    name: 'Baby Mushroom'
  sheep:
    enabled: true
    name: 'Sheep'
  babySheep:
    enabled: true
    name: 'Baby Sheep'
  rabbit:
    enabled: true
    name: 'Rabbit'
  babyRabbit:
    enabled: true
    name: 'Baby Rabbit'
  ocelot:
    enabled: true
    name: 'Ocelot'
  babyOcelot:
    enabled: true
    name: 'Baby Ocelot'
  pig:
    enabled: true
    name: 'Pig'
  babyPig:
    enabled: true
    name: 'Baby Pig'
  fox:
    enabled: true
    name: 'Fox'
  babyFox:
    enabled: true
    name: 'Baby Fox'
  cat:
    enabled: true
    name: 'Cat'
  babyCat:
    enabled: true
    name: 'Baby Cat'
  wolf:
    enabled: true
    name: 'Wolf'
  babyWolf:
    enabled: true
    name: 'Baby Wolf'
  bee:
    enabled: true
    name: 'Bee'
  polarBear:
    enabled: true
    name: 'Polar Bear'
  babyPolarBear:
    enabled: true
    name: 'Baby Polar Bear'
