name: PetsPlus
main: nl.mistermel.petsplus.PetsPlus
author: MisterMel
version: 1.1
description: 
commands:
  pets:
    description: The main command for PetsPlus.
    usage: /pets OR /petsplus
    aliases: [petsplus]